### ISSUE TITLE
Allow use of self signed certificates for dex

### ISSUE THREAD

**Issue by danielwhatmuff** [banzaicloud/jwt-to-rbac#6]
Hi there,

I'm hitting this when hooking up jwt-to-rbac to my dex test instance:

`provider init failed: Get https://dex.example.com:5556/.well-known/openid-configuration: x509: certificate signed by unknown authority.`

Is there a current way to allow insecure SSL or to provide a CA cert to use when connecting to dex?

**Comment by danielwhatmuff** [comment]
From a look at the `Dockerfile` I guess I could add my CA cert into the trust store during the build..

**Comment by bonifaido** [comment]
Hi @danielwhatmuff, yes that is currently the most viable option since we don't support custom CAs right now without code modifications. We will change the code to support custom CAs as well.

FYI: this is the part, that should be changed to support CAs outside the OS default ones: https://github.com/banzaicloud/jwt-to-rbac/blob/master/pkg/tokenhandler/token_handler.go#L41
